insert into type (name) values ('СЫР');
insert into type (name) values ('МОЛОКО');
insert into type (name) values ('МЯСО');
insert into type (name) values ('ТВОРОГ');
insert into type (name) values ('СЛАДКОЕ');
insert into product(name, id_type, price, expired_date) values ('Брестлитовский классический сыр', 1, 144, '2021-06-19');
insert into product(name, id_type, price, expired_date) values ('Шоколадное мороженное стаканчик', 5, 50, '2021-06-02');
insert into product(name, id_type, price, expired_date) values ('Голладский сыр', 1, 167, '2021-06-28');
insert into product(name, id_type, price, expired_date) values ('Пармезан', 1, 250, '2021-06-21');
insert into product(name, id_type, price, expired_date) values ('Моцарелла', 1, 120, '2021-06-01');
insert into product(name, id_type, price, expired_date) values ('Протеиновое мороженное', 5, 100, '2021-06-02');
insert into product(name, id_type, price, expired_date) values ('EKZO мороженное ведро', 5, 280, '2021-06-04');
insert into product(name, id_type, price, expired_date) values ('Индейка', 3, 300, '2021-06-24');
insert into product(name, id_type, price, expired_date) values ('Курица', 3, 250, '2021-06-23');
insert into product(name, id_type, price, expired_date) values ('Молоко отборное', 2, 57, '2021-06-18');
insert into product(name, id_type, price, expired_date) values ('Молоко 2.5%', 2, 47, '2021-06-15');
insert into product(name, id_type, price, expired_date) values ('Молоко обезжиренное', 2, 50, '2021-06-08');
insert into product(name, id_type, price, expired_date) values ('Творог пискаревский', 4, 60, '2021-06-18');
insert into product(name, id_type, price, expired_date) values ('Творог Савушкин', 4, 57, '2021-06-17');
insert into product(name, id_type, price, expired_date) values ('Творог зернистый', 4, 100, '2021-06-10');